spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wpp_gateway?useSSL=false&allowPublicKeyRetrieval=true
    username: wppuser
    password: wpppass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

wpp:
  base-url: http://localhost:8099
  secret-key: MINHACHAVESEGURA123
